modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/gavirchik/ToporDrovosekaMS3"

[[mods]]
modId="topor_drovoseka_ms3"
version="1.0.0"
displayName="Topor Drovoseka MS3"
description='''
Adds the ritual of creating a unique axe through dispenser, as Just_S player did on the MineShield 3 server.
'''
authors="gavirchik"
logoFile="logo.png"

[[dependencies.topor_drovoseka_ms3]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"